<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Fitness & Nutrition Plan</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            background-color: #1f2937; /* dark gray */
            color: #f9fafb; /* light text */
            line-height: 1.6;
            margin: 0;
            padding: 30px;
        }
        .container {
            max-width: 750px;
            margin: 0 auto;
            background-color: #111827; /* darker card bg */
            padding: 25px 30px;
            border-radius: 12px;
            box-shadow: 0 4px 12px rgba(0,0,0,0.4);
        }
        h1 {
            text-align: center;
            color: rgb(220,38,38); /* red */
            margin-bottom: 20px;
            font-size: 26px;
        }
        h2 {
            color: rgb(220,38,38);
            border-bottom: 1px solid #374151;
            padding-bottom: 5px;
            margin-top: 25px;
        }
        p, li {
            font-size: 14px;
            color: #e5e7eb; /* lighter gray */
        }
        .user-info {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 25px;
            font-size: 14px;
        }
        .user-info th {
            background-color: rgb(220,38,38);
            color: white;
            text-align: left;
            padding: 8px;
        }
        .user-info td {
            padding: 8px;
            border-bottom: 1px solid #374151;
        }
        .section {
            margin-top: 20px;
            padding: 15px;
            background-color: #1f2937;
            border-radius: 8px;
        }
        .footer {
            text-align: center;
            font-size: 12px;
            margin-top: 40px;
            color: #9ca3af;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Personalized Fitness & Nutrition Plan</h1>

        <!-- User info summary -->
        <table class="user-info">
            <thead>
                <tr>
                    <th>Field</th>
                    <th>Value</th>
                </tr>
            </thead>
            <tbody>
                <tr><td>Name</td><td>{{ $goal->name }}</td></tr>
                <tr><td>Goal</td><td>{{ $goal->fitness_goal }}</td></tr>
                <tr><td>Target Weight</td><td>{{ $goal->target_weight }} kg</td></tr>
                <tr><td>Deadline</td><td>{{ $goal->deadline }}</td></tr>
                <tr><td>Age</td><td>{{ $goal->age }}</td></tr>
                <tr><td>Gender</td><td>{{ $goal->gender }}</td></tr>
                <tr><td>Height</td><td>{{ $goal->height }} cm</td></tr>
                <tr><td>Current Weight</td><td>{{ $goal->current_weight }} kg</td></tr>
                <tr><td>Activity Level</td><td>{{ $goal->activity_level }}</td></tr>
                <tr><td>Workout Style</td><td>{{ $goal->workout_style }}</td></tr>
                <tr><td>Dietary Preferences</td><td>{{ implode(', ', $goal->dietary_preferences ?? []) }}</td></tr>
                <tr><td>Allergies</td><td>{{ $goal->food_allergies }}</td></tr>
                <tr><td>Medical Conditions</td><td>{{ $goal->medical_conditions }}</td></tr>
            </tbody>
        </table>

        <!-- AI generated plan -->
        <h2>Your 4-Week Plan</h2>
        <div class="section">
            {!! nl2br(e($plan)) !!}
        </div>

        <div class="footer">
            Generated by AJURNIE — Stay consistent and motivated 💪
        </div>
    </div>
</body>
</html>
